namespace Zombie3D
{
	public class AvatarInfo
	{
		public static string[] AVATAR_NAME = new string[10] { "JOE BLO", "PLUMBER", "NERD", "DOCTOR", "COWBOY", "SWAT", "MARINE", "B.E.A.F.", "PIRATE", "KUNOICHI" };

		public static string[] AVATAR_INFO = new string[12]
		{
			"JUST A REGULAR GUY, NOTHING SPECIAL ABOUT HIM.", "THIS STOUT LITTLE FELLA HAS THE STRENGTH OF A BEAR. EVEN THE HEAVIEST WEAPONS ARE A PIECE OF CAKE FOR HIM.", "YES, HIS GLASSES ARE THICK, BUT NOTHING GETS PAST THIS NERD. HIS POWERS OF OBSERVATION ARE ABSOLUTELY FIRST-RATE.", "WITH EXTENSIVE MEDICAL TRAINING, THIS GUY CERTAINLY KNOWS HOW TO TAKE CARE OF HIMSELF. HIS HEALTH REGENERATES AUTOMATICALLY.", "QUICK ON HIS FEET WITH FANTASTIC AGILITY, THIS GUY CAN GET AROUND.", "USED TO TAKING A BEATING, THIS EXPERIENCED ENFORCER HAS TONS AND TONS OF HP.", "THIS MILITARY TRAINED OFFICER DEFINITELY KNOWS HOW TO USE A WEAPON. HIS ACCURACY AND DAMAGE ARE UNMATCHED.", "BIO-ENHANCED ADVANCED FIGHTER. AN INCREDIBLY POWERFUL MYSTERIOUS WARRIOR FROM THE FUTURE, HIS ABILITIES IN EVERY AREA CAN ONLY BE DESCRIBED AS SUPERHUMAN.", "FRANCIS DRAKE IS A MAN CAPABLE OF OVERCOMING ALL SEA WAVES AND ALSO IS A HERO WHO HAS DEFEATED NUMEROUS NAVIES. HE IS REALLY THE PIRATE KING!", "Kunoichi's hunt for biological weapons led her here. With her agility and survival instincts, she can dance circles around the shambling undead.",
			"This brave fella smites the minions of evil while armored in nothing but his faith. His prayers are amply rewarded with gifts of health and wealth.", "THIS HARDY GUY IS NO STRANGER TO \nZOMBIE SEALS AND POLAR BEARS IN THE \nNORTH. THIS IS JUST ANOTHER STROLL IN \nTHE TUNDRA FOR HIM."
		};

		public static string[] AVATAR_INFO_SET = new string[12]
		{
			"JUST A REGULAR GUY, NOTHING SPECIAL \nABOUT HIM.", "THIS STOUT LITTLE FELLA HAS THE \nSTRENGTH OF A BEAR. EVEN THE \nHEAVIEST WEAPONS ARE A PIECE OF \nCAKE FOR HIM.", "YES, HIS GLASSES ARE THICK, BUT NOTHING \nGETS PAST THIS NERD. HIS POWERS OF \nOBSERVATION ARE ABSOLUTELY \nFIRST-RATE.", "WITH EXTENSIVE MEDICAL TRAINING, THIS \nGUY CERTAINLY KNOWS HOW TO TAKE \nCARE OF HIMSELF. HIS HEALTH \nREGENERATES AUTOMATICALLY.", "QUICK ON HIS FEET WITH FANTASTIC \nAGILITY, THIS GUY CAN GET AROUND.", "USED TO TAKING A BEATING, THIS \nEXPERIENCED ENFORCER HAS TONS AND \nTONS OF HP.", "THIS MILITARY TRAINED OFFICER \nDEFINITELY KNOWS HOW TO USE A \nWEAPON. HIS ACCURACY AND DAMAGE \nARE UNMATCHED.", "BIO-ENHANCED ADVANCED FIGHTER. AN \nINCREDIBLY POWERFUL MYSTERIOUS \nWARRIOR FROM THE FUTURE, HIS ABILITIES \nIN EVERY AREA CAN ONLY BE DESCRIBED \nAS SUPERHUMAN.", "FRANCIS DRAKE IS A MAN CAPABLE OF \nOVERCOMING ALL SEA WAVES AND ALSO \nIS A HERO WHO HAS DEFEATED \nNUMEROUS NAVIES. HE IS REALLY \nTHE PIRATE KING!", "Kunoichi's hunt for biological \nweapons led her here. With her \nagility and survival instincts, she \ncan dance circles around \nthe shambling undead.",
			"This brave fella smites the minions of \nevil while armored in nothing but his \nfaith. His prayers are amply \nrewarded with gifts of health and \nwealth.", "THIS HARDY GUY IS NO STRANGER TO \nZOMBIE SEALS AND POLAR BEARS IN THE \nNORTH. THIS IS JUST ANOTHER STROLL IN \nTHE TUNDRA FOR HIM."
		};

		public static string[] TIPS_INO = new string[39]
		{
			"Shotgun deals great damage to enemies at close range, whereas a terrible accuracy at long range.", "Aim first, and then shoot. This would save you a lot of ammo.", "The heavier the weapon you use the slower you run.", "Killing any enemy has a chance to drop an item.", "Boomers are very dangerous. They, however, make special noises.", "It is very important to observe enemies more and to keep moving.", "Nurses may attack you from long distance; remember to keep a distance from them.", "Be careful that grenade has a wide explosion scope!", "Be careful with that speedy guy, sometimes he will jump on you.", "Power-Up considerably boosts your damage in a short time.",
			"Red Cross can fully recover your character health instantly.", "Get a variety of items by shattering wooden cases on the battleground.", "It is crucial for combat to wisely use money to reconstruct weapons.", "Giants charge in a straight line. Keep moving to evade!", "AK-47 is an excellent weapon.", "Slow firing weapons can be very useful and practical after reconstruction.", "PGM is very powerful. All you need to do is wait until it automatically locks down an enemy and shoot.", "RPG-7 is not only powerful but also deals area damage.", "Every character has its unique abilities.", "Doctor automatically restores your health.",
			"Cowboy is good at running at an impressive high speed.", "Worker has amazing strength. Weight of weapons has no bearing on him.", "B.E.A.F is a very powerful warrior whose abilities are way better than others.", "It is easier for Nerd to get all sorts of items.", "Marine is a powerful solider, capable of dealing great damage to enemies.", "Swat wears armor with extraordinary stamina.", "Check ammo amount before battle.", "Weapons with high rate of fire consume ammo very quickly.", "Store is where you can buy various weapons and ammo.", "Weapons will be gradually unlocked as more levels are unlocked.",
			"Your running speed decreases while shooting.", "Watch your back and pay more attention to your surroundings.", "Once an item appears it will never disappear. Pick it up at the right time.", "Remember to equip equipment to put them in use after purchase.", "Great weapons need constant enhancing to see their values.", "Electric saw won't consume any ammo. Use it for your pleasure.", "Laser is tremendously powerful and able to penetrate enemies.", "Generally speaking, the more powerful the weapon the more expensive it is.", "When you feel the pinch, you'd better focus on 1 weapon."
		};
	}
}
