namespace Zombie3D
{
	public class MultiGameToturial
	{
		public static string[] Msg_Content = new string[9] { "CHOOSE A CO-OP NICKNAME SO \nYOUR FRIENDS CAN FIND YOU. \n(MAX 8 CHAR)", "CO-OP MODE IS NOW LIVE, TAP ANY \nAREA TO CHECK IT OUT!", "THIS IS THE CO-OP LOBBY, WHERE \nYOU CAN JOIN AN OPEN GAME.", "WAITING FOR HOST. IF YOU DON'T \nWANT TO WAIT, YOU CAN EXIT AND \nCHOOSE A DIFFERENT ROOM.", "YOU'VE CREATED A ROOM! NOW \nYOU JUST NEED AT LEAST 1 \nTEAMMATE TO START PLAYING.", "OH NO! YOU'RE DOWN! USE A \nCOMEBACK PACK OR WAIT FOR \nA TEAMMATE TO REVIVE YOU.", "THE ICON IN THE MIDDLE OF THE \nRADAR SHOWS YOUR LOCATION \nWHILE OTHER ARROWS SHOW \nTEAMMATE LOCATIONS. SKULLS \nSHOW DOWNED TEAMMATES.", "MAN DOWN! GO TO THE SKULL ON \nTHE MINIMAP AND SAVE HIM WITH \nA MEDPACK!", "UNLOCK CO-OP ACHIEVEMENTS TO \nGET SWEET REWARDS LIKE CASH, \nAVATARS, AND NEW WEAPONS!" };
	}
}
