namespace Zombie3D
{
	public class VSGameToturial
	{
		public static string[] Msg_Content = new string[7] { "WELCOME TO VS MODE! TAP A \nBUILDING ON THE MAP TO ENTER \nTHE VS LOBBY.", "THIS IS THE LOBBY, WHERE YOU CAN \nJOIN AN OPEN ROOM OR CREATE \nYOUR OWN.", "IF YOU ONLY WANT TO PLAY WITH \nYOUR FRIENDS, SET A PASSWORD \n(MAX 6 CHARS) FOR YOUR ROOM.", "WAITING FOR HOST. IF YOU DON'T \nWANT TO WAIT, EXIT AND CHOOSE \nA DIFFERENT ROOM.", "YOU HAVE CREATED A ROOM. YOU \nNEED AT LEAST 1 OTHER PLAYER TO \nBEGIN. EACH GAME CAN HAVE UP TO \n8 PLAYERS.", "YOU HAVE DIED. PLEASE WAIT TO \nRESPAWN.", "IN VS MODE, IT'S EVERY MAN FOR \nHIMSELF! RACK UP THE MOST KILLS \nIN 10 MINUTES FOR SOME SWEET REWARDS!" };
	}
}
